#ifndef COMMON_H
#define COMMON_H

#define ANIM_LINE_WIDTH 2
typedef enum{
    BUTTON_FIRST,
    BUTTON_SCALED,
    BUTTON_ENTER,
    BUTTON_LEAVE,
    BUTTON_PRESSED,
    BUTTON_DISABLE
}BUTTONSTATUS;
#endif // COMMON_H
